// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuHpVtKbtynG3p7ugQ4-JZTXcMFpFRRAE',
    appId: '1:704319069401:web:23aa7bbb0e1a0b4683f2c8',
    messagingSenderId: '704319069401',
    projectId: 'myfirebaseauth-72af9',
    authDomain: 'myfirebaseauth-72af9.firebaseapp.com',
    storageBucket: 'myfirebaseauth-72af9.appspot.com',
    measurementId: 'G-1VYYYTKD5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJsSIQ-lrES8mIGuwzJukyaG6aMs1qCU',
    appId: '1:704319069401:android:9ed4cb287c61f24683f2c8',
    messagingSenderId: '704319069401',
    projectId: 'myfirebaseauth-72af9',
    storageBucket: 'myfirebaseauth-72af9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP1v5DbO3XsyQNTpXqvMalQhBFXPARxlI',
    appId: '1:704319069401:ios:bd22b468680c6b0e83f2c8',
    messagingSenderId: '704319069401',
    projectId: 'myfirebaseauth-72af9',
    storageBucket: 'myfirebaseauth-72af9.appspot.com',
    iosBundleId: 'com.example.myFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP1v5DbO3XsyQNTpXqvMalQhBFXPARxlI',
    appId: '1:704319069401:ios:dd4cd6321cabf7d383f2c8',
    messagingSenderId: '704319069401',
    projectId: 'myfirebaseauth-72af9',
    storageBucket: 'myfirebaseauth-72af9.appspot.com',
    iosBundleId: 'com.example.myFirebaseAuth.RunnerTests',
  );
}
